---
title: "Assignment"
author: "Adrian Molière"
date: "3/4/2023"
output: html_document
---

```{r}
suppressPackageStartupMessages({
  library(AnnotationHub)
  library(ensembldb)
  library(GenomicRanges)
  library(epiwraps)
})
```


```{r}
ah <- AnnotationHub()

```



```{r }

query(ah, c("Mus Musculus", "2bit", "GRCm38", "102"))

mouse_twobit <- ah[["AH88477"]]

query(ah, c("Mus Musculus", "EnsDb", "GRCm38", "102"))

mouse_ensdb <- ah[["AH89211"]]

query(ah, c("Drosophila", "2bit", "BDGP6", "dna_sm"))

Dros_twobit <- ah[["AH49674"]]



```

How many different ensembl gene IDs and gene symbols are there for protein-coding genes?


```{r }
mouse_genes_protcod <- genes(mouse_ensdb, filter=TxBiotypeFilter("protein_coding"))

length(unique(mouse_genes_protcod$gene_id))

length(unique(mouse_genes_protcod$symbol))
```
Plot the distribution of the (spliced) length of protein-coding transcripts
■ (tip: this will require you to extract exons of protein-coding transcripts from the database, and split 
them by transcript, before summing the width of the exons of each transcript)
```{r}
mouse_exons <- exonsBy(mouse_ensdb, filter=TxBiotypeFilter("protein_coding"))

hist(sum(width(mouse_exons)), breaks = 150)

```


