---
title: "Assignment Week 4"
author: "Adrian Molière"
date: "2023-03-18"
output: html_document
---



```{r}
suppressPackageStartupMessages({
  library(AnnotationHub)
  library(rtracklayer)
  library(epiwraps)
  library(GenomicRanges)
})
ah <- AnnotationHub()
```


# Downloading the files

```{r, eval=FALSE}
download.file("https://www.encodeproject.org/files/ENCFF653YVR/@@download/ENCFF653YVR.bed.gz", "p300.bed.gz", mode = "wb") #p300

download.file("https://www.encodeproject.org/files/ENCFF331RHM/@@download/ENCFF331RHM.bed.gz", "H3K4me3.bed.gz", mode = "wb") #H3K4me3

download.file("https://www.encodeproject.org/files/ENCFF426IIV/@@download/ENCFF426IIV.bed.gz", "H3K4me1.bed.gz", mode = "wb") #H3K4me1

download.file("https://www.encodeproject.org/files/ENCFF212HAG/@@download/ENCFF212HAG.bed.gz", "H3K27ac.bed.gz", mode = "wb") #H3K27ac

download.file("https://www.encodeproject.org/files/ENCFF105NKG/@@download/ENCFF105NKG.bed.gz", "H3K27me3.bed.gz", mode = "wb") #H3K27me3


```


```{r}
p300_peaks <- rtracklayer::import("p300.bed.gz", format="narrowPeak")

H3K4me3_peaks <- rtracklayer::import("H3K4me3.bed.gz", format="narrowPeak")

H3K4me1_peaks <- rtracklayer::import("H3K4me1.bed.gz", format="narrowPeak")

H3K27ac_peaks <- rtracklayer::import("H3K27ac.bed.gz", format="narrowPeak")

H3K27me3_peaks <- rtracklayer::import("H3K27me3.bed.gz", format="narrowPeak")

```

# Calculating overlap
```{r}
#List of all peaks

peak_list <- list(P300 = p300_peaks, H3K4me3 = H3K4me3_peaks, H3K4me1 = H3K4me1_peaks, H3K27ac = H3K27ac_peaks, H3K27me3 = H3K27me3_peaks)

#apply overlaps function over all histone marks

all_overlaps <- lapply(peak_list[2:5], function(x) overlapsAny(p300_peaks, x))


```

# Table of overlap between p300 and all histone marks
```{r}
#output as a table

all_table <- sapply(all_overlaps, table)

all_table

#calculate ratio

all_overlaps_ratio <- lapply(all_overlaps, function(x) round((sum(x)/length(x)), digits = 4) )

unlist(all_overlaps_ratio)

```





