---
title: "Week 7 assignment"
author: "Adrian Molière"
date: "2023-04-27"
output: html_document
---

```{r}
suppressPackageStartupMessages({
  library(epiwraps)
  library(AnnotationHub)
  library(MotifDb)
  #library(memes)
  library(universalmotif)
  library(ensembldb)
  library(ggplot2)
})


ah <- AnnotationHub(localHub=TRUE)
ensdb <- ah[["AH89211"]] # mouse ensembldb object
```



```{r}
# get KLF4 and MAZ motif
motif_KLF4 <- query(MotifDb, c("KLF4","Mus"))[[1]]
motif2_KLF4 <- convert_motifs(motif_KLF4, class="TFBSTools-PFMatrix")

motif_MAZ <- query(MotifDb, c("MAZ","Mus"))[[1]]
motif2_MAZ <- convert_motifs(motif_MAZ, class="TFBSTools-PFMatrix")

genome <- ah[["AH68356"]]
# get the sequence for chr19:
chr19 <- import(genome)["19"]

# find motif occurences
moi_KLF4 <- motifmatchr::matchMotifs(motif2_KLF4, chr19, out="positions", p.cutoff=1e-5)[[1]]
# convert to GRanges (when using motifmatchr)
moi_KLF4 <- as(setNames(moi_KLF4,names(chr19)), "GRanges")

# find motif occurences
moi_MAZ <- motifmatchr::matchMotifs(motif2_MAZ, chr19, out="positions", p.cutoff=1e-5)[[1]]
# convert to GRanges (when using motifmatchr)
moi_MAZ <- as(setNames(moi_MAZ,names(chr19)), "GRanges")
```




## Plotting signal around the motif occurences

```{r}
# we prepare the list of tracks
tracks <- c("All cuts"="full_cuts.bw",
            "NF cuts"="NF_cuts.bw", "Mono centers"="mono_centers.bw")


# extract signals around the motif occurences
# we zoom in to 500bp around the motif centers, in windows of 5bp
sm_KLF4 <- signal2Matrix(tracks, moi_KLF4, w=5, extend=500) 
sm_MAZ <- signal2Matrix(tracks, moi_MAZ, w=5, extend=500) 

# plot the signals:
#KLF4
plotEnrichedHeatmaps(sm_KLF4, trim=0.95)
#MAZ
plotEnrichedHeatmaps(sm_MAZ, trim=0.95)


# the right to do this, however, is using a background normalization
# this we can do for instance using:
nf <- bwNormFactors(tracks, wsize=5L, useSeqLevels="19", nwind=5000L)
# then we apply the normalization factors:
smb_KLF4 <- rescaleSignalMatrices(sm_KLF4, nf)
smb_MAZ <- rescaleSignalMatrices(sm_MAZ, nf)

#KLF4
plotEnrichedHeatmaps(smb_KLF4, trim=0.95)
#MAZ
plotEnrichedHeatmaps(smb_MAZ, trim=0.95)
```